version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: etiketa_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

